---
title: "2025-09-26"
author: "benV"
date: "2025-09-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Half-life decay of projects}
### Set directory cos I'm not making a new project for each one of these
setwd(dirname(rstudioapi::getSourceEditorContext()$path))


### Load libraries
library(tidyverse)
library(colorspace)


### Generate dfs

# Projects and their half lives
project_half_lives <- tribble(
  ~Project, ~starting_hours_spent, ~half_life_in_hours,
  "Replacing the mirror in the bathroom", 12, 8,
  "Working on that Xenomorph speculative biology paper\nI started and never came back to", 18, 1,
  "Telling my friends they SHOULDN'T start a podcast", 1, 100,
  "Writing the compu-micro-bioinfo-molecu-net blog", 8, 100
)
 

### Functions

# Generate decay table to stop at 0 
generate_decay <- function(data) {
  max_steps <- ceiling(log2(data$starting_hours_spent / 0.01) * data$half_life_in_hours)
  time <- 0:max_steps
  value <- data$starting_hours_spent * (0.5)^(time / data$half_life_in_hours)
  tibble(
    Project = data$Project,
    time = time,
    hours_i_can_keep_this_up_for = value,
    half_life = data$half_life_in_hours
  ) %>%
    filter(value > 0.01)
}


### Manip dfs

# Calculate half-life for each project
project_decay <- project_half_lives %>%
  group_by(Project) |>
  group_map(~ generate_decay(.x), .keep = TRUE) |>
  bind_rows()


### Vis

# Line graph of project half-life decay
project_decay_line <- ggplot(project_decay, aes(x = time, y = hours_i_can_keep_this_up_for, colour = Project)) +
  geom_line(linewidth = 1) +
  scale_colour_discrete_divergingx(name = "Project", palette = "Zissou 1") +
  labs(
    x = "Time (hrs)",
    y = "Hours I can still keep this up for"
  ) +
  theme_bw()
project_decay_line
ggsave("project_decay_line.png", project_decay_line)

```



